# Generated by Django 6.1.1 on 2026-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amoint',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
